fix error using date based index on elasticsearch
sematext/logagent-js pull request #267
Opened 2020-12-01 12:57 UTC by aya

Thanks to @comel, this PR fixes #180 Elasticsearch indice with date error

2020-12-04 08:42 UTC, adnanrahic requested changes
Thanks a lot for this!
There is only one tiny linting edit I'd really like to see.
Then we can go ahead and merge it!

2020-12-04 08:42 UTC, adnanrahic commented on lib/plugins/output/elasticsearch.js
> +    if (data._index != undefined) {
To align with our linting rules, can you edit this to use strict inequality?

```suggestion
    if (data._index !== undefined) {
```

2020-12-04 08:42 UTC, adnanrahic commented on lib/plugins/output/elasticsearch.js
> +      if (data._index != undefined) {
To align with our linting rules, can you edit this to use strict inequality?

```suggestion
      if (data._index !== undefined) {
```

2020-12-10 09:34 UTC, aya commented
I applied you suggestions in latest commit, thanks for review !

2020-12-11 10:10 UTC, adnanrahic approved these changes

2020-12-11 10:11 UTC, adnanrahic commented
Sweet! Thanks for the contribution. I'll merge this now.

2020-12-11 10:11 UTC, merged