input-journald-upload: use removeFields from config, fix include/exclude test
sematext/logagent-js pull request #277
Opened 2021-05-17 07:52 UTC by mikolasan

After some old refactoring in `64f435872178ea16357e4bcad13b3a3db63f6802` the function `parseLine` became unused and still in the code, moreover `removeFields` parameter from configuration was not working. This PR returns usage of `removeFields` as it was before the refactoring.

Also fixed a bug with include/exclude parameter (hint: `log._SYSTEMD_UNIT !== log[_SYSTEMD_UNIT]`).

And also ignore messages in journald not coming from systemd services (I had audit and kernel syslog messages flooding my logs). This is a questionable change applied only to my setup, so please review it.

2021-07-01 12:22 UTC, otisg commented
WDYT @adnanrahic ?  Everything except the "And also ignore messages in journald not coming from systemd services " part?  We could leave the else + comment + comment out that return to disable this change?

2021-07-01 12:37 UTC, adnanrahic requested changes
This looks good! Removing the one `return` statement is the only thing to fix. Then we can get this merged. :smile:

2021-07-01 12:37 UTC, adnanrahic commented on lib/plugins/input/journald-upload.js
> +    return
```suggestion

```

2021-07-02 03:32 UTC, mikolasan commented on lib/plugins/input/journald-upload.js
> +    return
I agree. That is easy enough.

2021-07-02 11:46 UTC, adnanrahic approved these changes
Looks great!
Thanks a lot for this PR @mikolasan, I'll merge it right away.

2021-07-02 11:47 UTC, merged